## การบ้านจารย์ตั้ม แบบฝึกหัด Numpy

In [1]:
import numpy as np

# --- แบบฝึกหัด NumPy – การสร้างและใช้งานอาเรย์ ---

# 1D array: สร้างอาเรย์ขนาด 8 ที่มีเลขคี่จาก 1 ถึง 15
odd_array = np.arange(1, 16, 2)
print("1D array (odd numbers):", odd_array)

# 2D array: สร้างอาเรย์ 3 แถว 5 คอลัมน์ ที่มีค่าเป็น 9
array_2d = np.full((3, 5), 9)
print("\n2D array (3x5, filled with 9):\n", array_2d)

# 3D array: สร้างอาเรย์ 2 × 3 × 4 ที่มีค่าเป็น 0
array_3d = np.zeros((2, 3, 4))
print("\n3D array (2x3x4, filled with 0):\n", array_3d)
print("Shape of 3D array:", array_3d.shape)

# สร้างอาเรย์ที่มี 10 ค่า จาก 0 ถึง 5 โดยใช้ np.linspace()
linspace_array = np.linspace(0, 5, 10)
print("\nLinspace array (10 values from 0 to 5):", linspace_array)

# --- แบบฝึกหัด: NumPy Indexing & Slicing ---

default_array = np.array([1, 2, 3, 4, 5, 6])
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# เลือกสมาชิกตัวสุดท้าย
last_item = default_array[-1]
print("\nLast item of default_array:", last_item)

# เลือกสมาชิก index 1–3
slice_2_to_4 = default_array[1:4]
print("Slice from index 1 to 3:", slice_2_to_4)

# ค่าทั้งหมดในคอลัมน์ที่ 2 (index = 1)
column_2 = default_array_2d[:, 1]
print("Column 2 of default_array_2d:", column_2)

# แถวแรก 2 ตัวสุดท้าย
row1_last2 = default_array_2d[0, -2:]
print("Last 2 values of row 1:", row1_last2)

# ค่ามุมขวาล่าง
bottom_right = default_array_2d[-1, -1]
print("Bottom-right value of default_array_2d:", bottom_right)

# --- แบบฝึกหัด 3: การคำนวณทางคณิตศาสตร์ ---

x = np.array([1, 2, 3, 4])
result = x**2 + 2*x
print("\nResult of x^2 + 2x where x = [1,2,3,4]:", result)

1D array (odd numbers): [ 1  3  5  7  9 11 13 15]

2D array (3x5, filled with 9):
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]

3D array (2x3x4, filled with 0):
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Shape of 3D array: (2, 3, 4)

Linspace array (10 values from 0 to 5): [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Last item of default_array: 6
Slice from index 1 to 3: [2 3 4]
Column 2 of default_array_2d: [ 2  6 10]
Last 2 values of row 1: [3 4]
Bottom-right value of default_array_2d: 12

Result of x^2 + 2x where x = [1,2,3,4]: [ 3  8 15 24]
